### ISSUE TITLE
Create a version tag

### ISSUE THREAD

**Issue by mcamou** [birros/go-libp2p-grpc#1]
Thank you for this.

If I try to use `go-libp2p-grpc` as a library, I get the following:

```
$ go get github.com/birros/go-libp2p-grpc
go: github.com/birros/go-libp2p-grpc@v0.0.0: reading github.com/birros/go-libp2p-grpc/go.mod at revision v0.0.0: unknown revision v0.0.0
```

You'd need to add a `v0.0.0` tag (or `v0.0.1` or whatever) so that Go will be able to download it.

**Comment by birros** [comment]
Done.
Thx
